"""add optional customer to sales

Revision ID: a013802bc98d
Revises: 3872d5c3b768
Create Date: 2026-08-04 20:59:32.598118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a013802bc98d'
down_revision = '3872d5c3b768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_customer_id'), ['customer_id'], unique=False)
        batch_op.create_foreign_key('fk_sales_customer_id_customers', 'customers', ['customer_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sales_customer_id_customers', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_customer_id'))
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###
